### ISSUE TITLE
Error Message - 'VoiceRecorder has no web implementation'

### ISSUE THREAD

**Issue by ariari90** [tchvu3/capacitor-voice-recorder#1]
I have followed the exact steps as provided in angular ionic project. However, this line ->
VoiceRecorder.canDeviceVoiceRecord().then((result: GenericResponse) => console.log(result.value));

is throwing exception -
"core.js:4197 ERROR Error: Uncaught (in promise): VoiceRecorder does not have web implementation."

In the documentation, it says that canDeviceVoiceRecord() will never throw an exception. Could you please confirm whether this plugin does not support web implementation or am I doing something wrong?

Thank you so much to look into this.

**Comment by tchvu3** [comment]
This is because the plugin really does not have a web implementation,
you got this error when you used ios or android devices?
(the fact this function does not throw exception was meant for ios/android)

**Comment by ariari90** [comment]
I just tested now, it works perfectly in the device. Thank you so much!
