### ISSUE TITLE
Android canDeviceVoiceRecord gives false negative

### ISSUE THREAD

**Issue by pbackup12345** [tchvu3/capacitor-voice-recorder#10]
Checking out the Android version canDeviceVoiceRecord function it gives false while I can still record.
Looking at the code itself, I don't fully understand how it works.
As I can see it tries to create a MediaRecorder and then tries to start and stop it. However if I run this before asking for permission it will always fail.
So basically I don't see the purpose of the function, and in its current position (before asking for permission) it took me a lot of time to realize that I should simply not use this for right now.

**Comment by tchvu3** [comment]
thanks, I will check it and release a fix

**Comment by tchvu3** [comment]
I fixed the problem, actually I made sure to always return true as to not break any project dependent on this plugin.
There is no real reason to check this as any phone will have microphone
