### ISSUE TITLE
Questions regarding the plugin

### ISSUE THREAD

**Issue by lucasmrl** [tchvu3/capacitor-voice-recorder#12]
@tchvu3 thanks for your amazing work here!

I'm about to start a simple journal app where I can record an entry and later on add some more information to that recording.
A few questions:

- After you stop the recording, where the file is saved? in a temp folder?
- If yes, can I use the "Filesystem" plugin from Capacitor to create/move this file to a permanent folder that will be created when the user install my app?

Thank you!

**Comment by tchvu3** [comment]
Hey friends. i'm happy you like this plugin.
Regarding your question, as you can see in the snipped below from
the android impl:

```
    private void setRecorderOutputFile() throws IOException {
        File outputDir = context.getCacheDir();
        outputFile = File.createTempFile("voice_record_temp", ".aac", outputDir);
        outputFile.deleteOnExit();
        mediaRecorder.setOutputFile(outputFile.getAbsolutePath());
    }
```

I output the recording to the cache directory on the phone and mark it for delete.
this means that the file will be removed as soon as the java process ןד shutdown (this is a precaution).
Plus, notice that in the `stopRecording` method I also manually delete the recording file:  `mediaRecorder.deleteOutputFile();`

which means all I return is the base64 string that represent the recording while
the file that holds the recording is long gone.
you can of course just take this base64 string and save it to the file system using the
appropriate "Filesystem" plugin
