### ISSUE TITLE
On iOS the plugin does not work well with other audio playback plugins

### ISSUE THREAD

**Issue by talkonadmin** [tchvu3/capacitor-voice-recorder#13]
Upon recording start, the plugin sets the AVAudioSession category to record only which prevents the app from playing sounds with other audio plugins (e.g. native-audio).
My solution was to set the category to playAndRecord but I assume the proper solution is to save the current category and restore it after recording stops.

**Comment by azizcreativitykw** [comment]
@tchvu3 
is this is fixed now?

**Comment by tchvu3** [comment]
@talkonadmin @azizcreativitykw this issues is resolved
