### ISSUE TITLE
Support Capacitor v4

### ISSUE THREAD

**Issue by MalulTal** [tchvu3/capacitor-voice-recorder#15]
Support Capacitor v4

import VoiceRecorder from Plugins, we have this deprecation:

@deprecated
Provided for backwards compatibility for Capacitor v2 plugins. Capacitor v3 plugins should import the plugin directly. This "Plugins" export is deprecated in v3, and will be removed in v4.

import VoiceRecorder from capacitor-voice-recorder, we have this error on native devices:
Error: VoiceRecorder does not have web implementation

**Comment by tchvu3** [comment]
There is no capacitor v4 as of now, and I've already updated the plugin to support capacitor v3.
In the last commit, I've added web support. please make sure that you have the latest version
of the plugin and that you import it directly and not from the Plugins module.
if you're still having issues please let me know and I will provide a simple code snippet
