### ISSUE TITLE
"recordDataBase64" sometimes contains the mimeType

### ISSUE THREAD

**Issue by natoromano** [tchvu3/capacitor-voice-recorder#16]
Hello,

I noticed that:
- on web `recordDataBase64` contains the mimeType and encoding, e.g.: `data: audio/webm;codecs=opus; base64, <actual encoding>`
- on mobile it it just the raw encoding

Is that working as intended?

Thanks!

**Comment by tchvu3** [comment]
It does not, thanks for bringing this issue to my attention, I will fix it very soon

**Comment by KevinToala** [comment]
same behavior :/

**Comment by tchvu3** [comment]
fixed in the latest version :)
