### ISSUE TITLE
Unexpectedly found nil crash

### ISSUE THREAD

**Issue by santekotturi** [tchvu3/capacitor-voice-recorder#18]
I've found this plugin fatally crashes when my phone is in an audio call and I try to record an audio. I've got everything wrapped in try catch blocks and it still fatally crashes the app. 

Xcode throws an error here, something about trying to implicitly unwrap nil

```
    public func stopRecording() {
        do {
            audioRecorder.stop()
            try recordingSession.setActive(false)
            try recordingSession.setCategory(originalRecordingSessionCategory)
            originalRecordingSessionCategory = nil
            audioRecorder = nil
            recordingSession = nil
            status = CurrentRecordingStatus.NONE
        } catch {}
    }
    ```

**Comment by tchvu3** [comment]
can you share the call stack??

**Comment by karimBenBechir** [comment]
Hello guys, 
Thank you very much providing the plugin ! 
I have same issue here, when microphone is used by an other app, the flow is corrupted and it crashes the app returning  "Unexpectedly found nil while implicitly unwrapping an Optional value".
I've trying many walkarounds, such as trycatch, check for ability to record via the "canDeviceVoiceRecord" method, catch startRecording throwing exception but still can't figure out what could be the solution.
what do you mean by share the call stack ?
