### ISSUE TITLE
Limitations of the plugin

### ISSUE THREAD

**Issue by garbit** [tchvu3/capacitor-voice-recorder#19]
Hi there,

I'm looking to use this plugin in my next project and I wondered if there were any limitations in regards to the maximum duration of the audio file?

As I understand it from a [previous question regarding file management](https://github.com/tchvu3/capacitor-voice-recorder/issues/12) the library creates a temp file which is then base64 encoded and then deleted. The base64 string is bubbled back up as a string to the web application and at this point is there a theoretical maximum size on this?

My use case is long audio recordings (1hr let's say) and I'm wondering if I'll face any issues.

Thanks in advance.

**Comment by tchvu3** [comment]
Hey friend.
personally, I haven't seen or encountered any type of limitation regarding the limit of the base64 string
that I can pass (from either capacitor or vendors).
I've used this plugin to record files that were about 30 min long without any problem.
with that being said, it would be best for you to check for yourself if there are any problems with voice recordings
that are that long (and you can also update me in case you find any so we might find a solution).
