### ISSUE TITLE
Add LICENSE.

### ISSUE THREAD

**Issue by damngamerz** [tchvu3/capacitor-voice-recorder#2]
Hey I was thinking why the capacitor-community doesn't have a plugin for audio recording.
https://github.com/capacitor-community/media/issues/12
I will create a PR in media plugin to add the same functionality.
For which I might take some help for here. But before I do that,
I'm guessing this is open-source. Can you add the LICENSE?

A quick suggestion,
I'm afraid of using this plugin cause of maintainability.
Maybe you can also ask capacitor community to add this repo officially in order to receive more contributors.

**Comment by tchvu3** [comment]
my plugin was already part of the community list.
now that i look at it after the capacitor team revamped
their site they apparently updated the community plugins repo
and i need to sent my plugin to them again.

on another topic, i've added the license file (MIT) as you suggested.

adding additional contributors would be nice.
as i use this plugin in my own projects i always make sure
to keep it up to date, but adding new features are not
likely as it does what i need it to do.

**Comment by damngamerz** [comment]
That would be great. I will start using this in the meanwhile :)
Thanks for the changes.
