### ISSUE TITLE
Update please capacitor to 4v

### ISSUE THREAD

**Issue by Hambat** [tchvu3/capacitor-voice-recorder#24]

**Comment by vinaykortikere** [comment]
@Hambat I have forked and made changes to upgrade to Capacitor V4 - https://github.com/vinaykortikere/capacitor-voice-recorder

You can clone the repo to your local file system and then npm install from the file system in your capacitor project and use it if you need.

@tchvu3  Please review my changes in forked repo and please publish the V4 versioned plugin to NPM registry.

**Comment by tchvu3** [comment]
After checking the changes between v3 and v4 i've decided to recreate the plugin from the v4 template, and test it thoroughly just to be safe. should be up and running by Sunday. even so, thank you for taking the time to update the plugin

**Comment by tchvu3** [comment]
The update for version 4 is up
