### ISSUE TITLE
Capacitor 6 support

### ISSUE THREAD

**Issue by alex-fib** [tchvu3/capacitor-voice-recorder#45]
Add support for capacitor 6

**Comment by tchvu3** [comment]
In the coming days I will.
I'll also address each issue that was opened

**Comment by Eraldo** [comment]
> In the coming days I will. I'll also address each issue that was opened

FYI: I already tried using the v5 version of this plugin together with Capacitor v6 and things seem to still work.
Wanted to let you know as I think that's a good sign and might help reassure some people that this might come soon.

As I already upgraded to capacitor v6 and I had to add --force in all of my workflows feels very hacky. 😅 
So, I am thankful that you are doing this soon, so I can remove the workaround. 🙏

**Comment by alex-fib** [comment]
@tchvu3 Any update?

**Comment by Eraldo** [comment]
> oming days I will.
> I'll also address each issue that was opened

Bump? :D

**Comment by Eraldo** [comment]
@tchvu3 I'm getting a bit worried. Are you ok? 🥺

**Comment by niconaso** [comment]
@tchvu3 I created this [PR](https://github.com/tchvu3/capacitor-voice-recorder/pull/47) that adds support for Capacitor 6. @Eraldo can you test it?

**Comment by Eraldo** [comment]
> @tchvu3 I created this [PR](https://github.com/tchvu3/capacitor-voice-recorder/pull/47) that adds support for Capacitor 6. @Eraldo can you test it?
Do you by any chance know how I can install from a PR via poetry? I didn't manage to get it to work.
That being said it looks good to me. :)

**Comment by Eraldo** [comment]
> @tchvu3 I created this [PR](https://github.com/tchvu3/capacitor-voice-recorder/pull/47) that adds support for Capacitor 6. @Eraldo can you test it?

```
"capacitor-voice-recorder": "github:tchvu3/capacitor-voice-recorder#pull/47/head",
```
=> Works nicely for me. :)
(Did some manual frontend record testing as well.) 👍

**Comment by midomario** [comment]
> "capacitor-voice-recorder": "github:tchvu3/capacitor-voice-recorder#pull/47/head",

How can I test it (Install this PR) ?

**Comment by SergeiPleshkov** [comment]
@tchvu3 how is it going?

**Comment by midomario** [comment]
Hi, any suggested alternative package for V6 ?

**Comment by SergeiPleshkov** [comment]
For now I just use npm i --force, no bugs found (tested on iOS devices). Just waiting this issue to be resolved to remove --force from ci/cd pipelines.

**Comment by qmarcos** [comment]
@tchvu3 any updates on this? 

As @Eraldo anticipated, updating to Capacitor 6 is mandatory for projects in order to support API 34 with Android 14, with the deadline on August 31st.

I hope you can review the @niconaso PR to release a Capacitor 6 compatible version soon.

Thanks in advance!

**Comment by Snargol** [comment]
@tchvu3 any updates on this? 😇

**Comment by qmarcos** [comment]
> Hi, any suggested alternative package for V6 ?

cc @midomario 

I finally have used the approach commented by @Eraldo , installing the version from the PR of @niconaso 
It works fine with Capacitor 6, although it's not a good thing to use the package from a PR...

If you are looking for some plugin alternatives, this one (seems to be maintained) could be fit your needs: https://github.com/mozartec/capacitor-microphone

Anyway, it would be nice that @tchvu3 review the PR and update the plugin with it. 

On the other hand, I aim to all of you who wants an update to make some donations to him to support his work here: https://buymeacoffee.com/tchvu3

Hope it helps!

**Comment by tchvu3** [comment]
Thanks everyone for their interest in the plugin,
and thanks to @qmarcos for the nice gesture, its not taken for granted.
The plugin is not dead, and i will updated it in the following days, i was just very busy in my personal life.

**Comment by kstruempf** [comment]
Hi @tchvu3, great to hear that the plugin is not dead :) 

Do you think adding CI/CD pipeline would help you and make maintenance a bit easier in the future?
I am thinking of something similar to what is used by the ionic team on the official plugins:
* [Verification](https://github.com/ionic-team/capacitor-plugins/blob/94211377433c7d26208aedbcee8bb82f3d0985ae/.github/workflows/ci.yml)
* [Deployment](https://github.com/ionic-team/capacitor-plugins/blob/94211377433c7d26208aedbcee8bb82f3d0985ae/.github/workflows/publish-npm-latest.yml)

If something like that is needed, please let me know and I would be happy to contribute.

**Comment by tchvu3** [comment]
Finished updating to v6.
@kstruempf thats awesome, I hope it will be useful to you and your company.
I will anyway continue to maintain the plugin as needed
