### ISSUE TITLE
API enhencement request

### ISSUE THREAD

**Issue by mindstorm38** [tchvu3/capacitor-voice-recorder#6]
This plugin is what I was searching for some time in order to replace the old deprecated cordova plugin media, but some functions are missing for a complete API:
- Functions for pausing and resuming recording, it seems possible since the the `MediaRecorder ` class support `pause` and `resume` methods.
- Add parameters to `VoiceRecorder.stopRecording` to change the return value format. In my case I will record for dozens of minutes and the base64 encoded string will be really too large, it would be nice to have a parameter to specify that we want to move the temporary file to another location instead of returning its content. For example `VoiceRecorder.stopRecording()` could take an options object like
```ts
interface StopOptions { 
    move?: string;
}
```
In this case if move is `!= null`, the plugin move the file to the given location (this could be an URI returned by `Filesystem.getUri`) and return this location instead of returning the file content as encoded string.

If you don't have enough time to do it, I will try to implement this (only for Android because I have no idea how to do this on iOS).

**Comment by tchvu3** [comment]
As I answered to #7 this plugin was written for my own use case, and I shared this plugin as I thought it might help other people in similar situation.
I really wish i could add additional features that people ask for, but I just don't have the time to put on these features right now

**Comment by mindstorm38** [comment]
No problem! Thank you anyway because I used it to write my own plugin.
