### ISSUE TITLE
Request: Update example & code to capacitor 3.0 syntax

### ISSUE THREAD

**Issue by qpwo** [tchvu3/capacitor-voice-recorder#7]
Details of differences here:
https://capacitorjs.com/docs/updating/3-0

**Comment by inexuscore** [comment]
Is this repository actively maintained? I was excited to get started with this but it doesn't work on Capacitor 3.

```
Error: node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'. Types of property 'Plugins' are incompatible.  

Property 'VoiceRecorder' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'. export interface CapacitorInstance extends CapacitorGlobal {
```

**Comment by tchvu3** [comment]
As I made this plugin primarily for my own use case I could not find the time to add additional features (as requested by some people). with that said, I'm about to update my project to ver 3 of Capacitor and so I will updated this plugin in the coming days

**Comment by inexuscore** [comment]
@tchvu3 Fantastic, thank you. Ionic+Capacitor is great but it's a shame that there aren't official plugins for the essentials.

**Comment by tchvu3** [comment]
The plugin has been updated to capacitor v3.
though I didn't have time to test it thoroughly.
so if you had a chance to drop a comment after you try it please let me know if you had any problem.
