### ISSUE TITLE
IOS error on build

### ISSUE THREAD

**Issue by pbackup12345** [tchvu3/capacitor-voice-recorder#9]
Thank you for the plugin. It's a great help.
It works for Android great however at build time I receive the following error message in XCode. I tried what I could but I have no idea where the error comes from. Latest XCode. Anything known?

`Ld /Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Products/Release-iphoneos/CapacitorVoiceRecorder/CapacitorVoiceRecorder.framework/CapacitorVoiceRecorder normal (in target 'CapacitorVoiceRecorder' from project 'Pods')
    cd /Users/peterszeman/Documents/chattutor/ios/App/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios12.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L/Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Products/Release-iphoneos/CapacitorVoiceRecorder -F/Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Products/Release-iphoneos/CapacitorVoiceRecorder -F/Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Products/Release-iphoneos/Capacitor -F/Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Products/Release-iphoneos/CapacitorCordova -filelist /Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Intermediates.noindex/Pods.build/Release-iphoneos/CapacitorVoiceRecorder.build/Objects-normal/arm64/CapacitorVoiceRecorder.LinkFileList -install_name @rpath/CapacitorVoiceRecorder.framework/CapacitorVoiceRecorder -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Intermediates.noindex/Pods.build/Release-iphoneos/CapacitorVoiceRecorder.build/Objects-normal/arm64/CapacitorVoiceRecorder_lto.o -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Intermediates.noindex/Pods.build/Release-iphoneos/CapacitorVoiceRecorder.build/Objects-normal/arm64/CapacitorVoiceRecorder.swiftmodule -framework Capacitor -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Intermediates.noindex/Pods.build/Release-iphoneos/CapacitorVoiceRecorder.build/Objects-normal/arm64/CapacitorVoiceRecorder_dependency_info.dat -o /Users/peterszeman/Library/Developer/Xcode/DerivedData/App-beknefqbwxnrjvgtzlguknerdxdw/Build/Products/Release-iphoneos/CapacitorVoiceRecorder/CapacitorVoiceRecorder.framework/CapacitorVoiceRecorder

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_VoiceRecorderPlugin", referenced from:
      __OBJC_$_CATEGORY_VoiceRecorderPlugin_$_CAPPluginCategory in VoiceRecorder-325378aea09476210eff33d5adb008ecf712f34df2b415ce0d8240f209ac93ab.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`
asdf
`

**Comment by hpgiorgio** [comment]
I have the same problem too.

**Comment by pbackup12345** [comment]
This is a clean create-react-app application producing the error: https://github.com/pbackup12345/voice-recorder

**Comment by Josepavese** [comment]
Same problem here

**Comment by tchvu3** [comment]
I'm on it

**Comment by pbackup12345** [comment]
I think I found the error itself:
In this file:
/node_modules/capacitor-voice-recorder/ios/Plugin/VoiceRecorder.m

CAP_PLUGIN(VoiceRecorderPlugin, "VoiceRecorder",
should read
CAP_PLUGIN(VoiceRecorder, "VoiceRecorder",
should read

**Comment by tchvu3** [comment]
yes i know it comes from the definition, it was because I changed the class name but forgot
to update the definition. i'm fixing another small bug with android and will upload the fixes for android and ios together

**Comment by tchvu3** [comment]
uploaded the fix, please let me know if any other error occures
